spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;INIT=runscript from 'classpath:sql/demo_h2.sql'
    username: sa
    password: ""

mybatis-plus:
  global-config:
    db-config:
      db-type: H2
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl